### ISSUE TITLE
[CDS-Toolkit] - Unable to retrieve accounts from shareable endpoint

### ISSUE THREAD

**Issue by malshaniS** [wso2/financial-services-accelerator#141]
**Description:**

- Observed the below error in profile selection page of consent authorisation flow.

<img width="1164" alt="Screenshot 2024-10-11 at 11 49 37 AM" src="https://github.com/user-attachments/assets/4f3020a9-7067-442d-b378-b688b360f721">

- This issue occurred as it cannot retrieve data from shareable endpoint. Getting below error when we try to retrieve accounts from. shareable accounts endpoint.

<img width="1146" alt="Screenshot 2024-10-11 at 11 51 28 AM" src="https://github.com/user-attachments/assets/5f27a84b-f2df-4110-81f8-278937eaf58e">

IS Server Logs before the new patch
```
TID: [-1234] [] [2024-10-11 06:19:32,153] [1242ac9e-e611-460c-a75d-fa99c62e3f50] ERROR {com.wso2.openbanking.accelerator.authentication.data.publisher.internal.AuthenticationDataPublisherServiceComponent} - Failed to retrieve the authentication step relating to the authentication
TID: [-1234] [api/openbanking/consent] [2024-10-11 06:19:34,418] [581ef53a-4353-434f-9551-5b8800fcbec0] ERROR {org.wso2.openbanking.cds.consent.extensions.authorize.utils.CDSDataRetrievalUtil} - Retrieving sharable accounts failed
TID: [-1234] [api/openbanking/consent] [2024-10-11 06:19:34,418] [581ef53a-4353-434f-9551-5b8800fcbec0] ERROR {org.wso2.openbanking.cds.consent.extensions.authorize.impl.retrieval.CDSAccountListRetrievalStep} - Unable to load accounts data for the user: admin@wso2.com@carbon.super
```

IS server logs after the new patch
```
TID: [2024-10-11 06:19:33,733] ERROR {com.wso2.openbanking.accelerator.data.publisher.common.OBThriftDataPublisher} - Error while setting payload to publish data. {com.wso2.openbanking.accelerator.data.publisher.common.OBThriftDataPublisher}
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**
1. Send consent authorisation request.
2. Verify the profile selection page.

**Related Issues:**

**Comment by anjuchamantha** [comment]
This issue has caused due to a patched jar (cds demo backend war) which contained changes to remove spring in an incorrect manner.
 
Fixed with 

- https://github.com/wso2/reference-implementation-consumerdatastandards-au/pull/16

**Comment by malshaniS** [comment]
Verified as Fixed
