### ISSUE TITLE
[OB3] - Real time notification sends to all the callback servers regardless of event type when TPP has multiple subscriptions

### ISSUE THREAD

**Issue by malshaniS** [wso2/financial-services-accelerator#168]
**Description:**
According to the expected behaviour the real time event notification should redirect to the relevant server based on the subscribed event type. But in actual scenario, the real time notification sends to all the callback servers regardless of event type when TPP has multiple subscriptions. 

1. Create a subscription for consent revoke and resource update separately with different callback urls.

<img width="689" alt="Screenshot 2024-10-30 at 11 38 54 PM" src="https://github.com/user-attachments/assets/4f2337e9-655f-438a-b6b6-d2a656f23453">

2. Create an event for consent revocation.
3. Notification should received only by the server "http://localhost:5055/sample-tpp-server".
4. But it received by both the servers.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**
[Any related issues such as sub tasks, issues reported in other repositories (e.g component repositories), similar problems, etc. ]

**Comment by VimukthiRajapaksha** [comment]
Fixed with 11887 update. 

Release versions
wso2-obam-accelerator 	3.0.0.66.full
wso2-obiam-accelerator 	3.0.0.112.full
