### ISSUE TITLE
[CDSToolkit][ConsentMgr] - Software Product is empty for new Consents

### ISSUE THREAD

**Issue by malshaniS** [wso2/financial-services-accelerator#172]
**Description:**
Software Product is empty for new Consents in consent manager portal

<img width="1717" alt="Screenshot 2024-11-04 at 2 25 16 PM" src="https://github.com/user-attachments/assets/2a425e57-1991-4fd3-b93c-7d06adfbd69b">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**
1. Create an application.
2. Create a consent from the application.
3. Verify the consent manager dashboard

**Related Issues:**
[Any related issues such as sub tasks, issues reported in other repositories (e.g component repositories), similar problems, etc. ]

**Comment by malshaniS** [comment]
Verified the new patch as FIxed

**Comment by aka4rKO** [comment]
Closing since the fix is released
