### ISSUE TITLE
[CDSToolkit][ConsentMgr] - Incorrect revocation date display under consent amendment history for migrated consents

### ISSUE THREAD

**Issue by malshaniS** [wso2/financial-services-accelerator#175]
**Description:**
Consent created date is displayed the consent revocation date under consent amendment history of a migrated consent.

<img width="1698" alt="Screenshot 2024-11-05 at 10 16 41 AM" src="https://github.com/user-attachments/assets/6cef8184-a876-4adc-8cb3-1f2103a09a89">

The expected value should be the current date and revoked time as it is withdrawn today.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**
1. Goto migrated active consent.
2. Revoke the consent.
3. Verify the date of the consent amendment history tab.

**Related Issues:**

**Comment by anjuchamantha** [comment]
Consent updated time coming from backend response is wrong, resulting in consent amended history times to be wrong including revocation time.

**Comment by malshaniS** [comment]
Verified as Fixed
