### ISSUE TITLE
[OB3] Need to validate CIBA flow in accelerator with latest base products

### ISSUE THREAD

**Issue by hasithakn** [wso2/financial-services-accelerator#18]
**Description:**
Need to verify the CIBA flow in the accelerator with latest base products

**Suggested Labels:**
CIBA

**Suggested Assignees:**

**Affected Product Version:**
OB3

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**
[Any related issues such as sub tasks, issues reported in other repositories (e.g component repositories), similar problems, etc. ]

**Comment by VimukthiRajapaksha** [comment]
This will be tracked by https://github.com/wso2/financial-services-accelerator/issues/233.
