### ISSUE TITLE
[CDSToolkit] -  Consent revocation request fails when the client assertion doesn't have the ```iat``` value

### ISSUE THREAD

**Issue by Akila94** [wso2/financial-services-accelerator#185]
**Description:**
The arrangement revocation request fails when the client assertion doesn't contain the optional ```iat``` value. This needs to be fixed.

**Suggested Labels:**
CDS toolkit

**Suggested Assignees:**

**Affected Product Version:**
OB3 CDS toolkit

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Perform the arrangement revocation request without the ```iat``` element in the client assertion.

**Related Issues:**

**Comment by Akila94** [comment]
Verified as fixed

**Comment by imesh94** [comment]
https://github.com/wso2-enterprise/wso2-ob-internal/issues/882
